package com.wesley.dualsensebattery;
import android.Manifest;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Typeface;import android.os.*;import android.provider.Settings;import android.view.Gravity;import android.widget.*;
public class MainActivity extends Activity{
 TextView status;static final int REQ=10;
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER_HORIZONTAL);int p=dp(24);l.setPadding(p,dp(48),p,p);TextView t=new TextView(this);t.setText("🎮 DualSense Battery");t.setTextSize(28);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);l.addView(t);TextView s=new TextView(this);s.setText("\nBateria do controle na barra de notificações.");s.setTextSize(16);s.setGravity(Gravity.CENTER);l.addView(s);status=new TextView(this);status.setTextSize(18);status.setGravity(Gravity.CENTER);status.setPadding(0,dp(28),0,dp(28));l.addView(status);Button a=new Button(this);a.setText("ATIVAR NOTIFICAÇÃO");a.setOnClickListener(v->start());l.addView(a);Button stop=new Button(this);stop.setText("PARAR MONITOR");stop.setOnClickListener(v->{stopService(new Intent(this,BatteryMonitorService.class));status.setText("Monitor parado.");});l.addView(stop);setContentView(l);refresh();}
 void start(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ);}else go();}
 void go(){startForegroundService(new Intent(this,BatteryMonitorService.class));status.setText("Monitor ativo. Abra a barra de notificações.");}
 void refresh(){DualSenseInfo i=DualSenseReader.read();if(!i.connected)status.setText("Conecte o DualSense por Bluetooth e toque em ATIVAR.");else if(i.percent>=0)status.setText("DualSense conectado • "+i.percent+"%\n"+i.stateText);else status.setText("DualSense conectado.\nBateria não exposta pelo Android.");}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ)go();}int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
